import {
    useParams,
} from "react-router-dom";

import PageContainer
from "../../components/layout/PageContainer";

function AIAnalysisPage() {

    const {
        documentId,
    } = useParams();

    return (

        <PageContainer
            title="🤖 AI Analysis"
            subtitle="Medical report generated by AI."
        >

            <div className="rounded-xl bg-slate-50 p-5">

                <p className="font-semibold">

                    Document ID

                </p>

                <p className="mt-2 text-gray-600">

                    {documentId}

                </p>

            </div>

            <div className="grid grid-cols-2 gap-5 mt-6">

                <div className="rounded-xl border p-5">
                    Patient Name
                </div>

                <div className="rounded-xl border p-5">
                    Hospital
                </div>

                <div className="rounded-xl border p-5">
                    Charges
                </div>

                <div className="rounded-xl border p-5">
                    Confidence
                </div>

            </div>

        </PageContainer>

    );

}

export default AIAnalysisPage;